language: node_js

notifications:
  email: false

dist: trusty
sudo: required
cache: npm

install:
  - npm install
  - npm install -g codecov


jobs:
  include:
    - stage: "Test"
      name: "Node 8"
      node_js: "8"
      script: npm run coverage

    - name: "Node 9"
      node_js: "9"
      script: npm run coverage

    - name: "Node 10"
      node_js: "10"
      script: npm run coverage

    - name: "Node 11"
      node_js: "11"
      script:
        - npm run build
        - npm run coverage && codecov
      after_success:
        - npm run typedoc
        - cp jekyll/_config.yml docs/_config.yml
      
      deploy:
        - provider: pages
          skip_cleanup: true
          local_dir: docs/
          github_token: $GITHUB_TOKEN
          on:
            branch: master
        - provider: npm
          skip_cleanup: true
          email: $EMAIL
          api_key: $NPM_API_KEY
          on:
            branch: release
