language: node_js
node_js:
  - "10"
dist: trusty
sudo: required
cache: npm

if: branch = master

install: npm ci

script: npm run test

after_success:
  - npm run typedoc

deploy:
  - provider: pages
    skip_cleanup: true
    local_dir: docs/
    github_token: $GITHUB_TOKEN
    on:
      tags: true
